# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://www.iosdev.nl
title: Bart Hoffman Producties
email: info@barthoffman.nl
author: Bart Hoffman
description: >  
  Bart Hoffman, Freelance developer for iOS and Mac OS X, based in Amsterdam
copyright: 'Copyright &copy; 2015 Bart Hoffman. All Rights Reserved.'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/barthoffman
  - title: github
    url: https://github.com/barthoffman
  - title: linkedin
    url: https://www.linkedin.com
